# file: docker-compose.infra.yml

version: '3.8'

services:
  # --- Redis Service for Short-Term Memory ---
  redis:
    image: redis:7-alpine
    container_name: tgb-local-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./volumes/redis-db:/data
    restart: always

  # --- ChromaDB Service for Vector Storage (RAG) ---
  chroma:
    image: ghcr.io/chroma-core/chroma:1.0.13
    container_name: tgb-local-chroma
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./volumes/rag-db:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
    restart: always

volumes:
  redis-db:
  chroma-db: