# file: docker-compose.infra.yml

version: '3.8'

services:
  # --- Common Infrastructure Services ---
  redis:
    image: redis:7-alpine
    container_name: tgb-local-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-db:/data
    restart: always

  # --- MLOps Orchestration & Tracking ---
  # [ISSUE-26] ZenML Server for orchestrating pipelines.
  zenml-server:
    image: ghcr.io/zenml-io/zenml-server:0.57.0 # Pinned to a specific version for stability.
    container_name: tgb-local-zenml
    ports:
      - "127.0.0.1:8237:8080"
    volumes:
      - zenml-data:/app/zenml
      - ./volumes/rag-source-docs:/rag-source-docs
    restart: always

  # --- [ISSUE-28] Start of changes: Vector DB Migration ---
  # Vector DB services are now managed via profiles.
  # Qdrant is the new default, Chroma is the fallback.

  qdrant:
    image: qdrant/qdrant:v1.9.2
    container_name: tgb-local-qdrant
    ports:
      - "127.0.0.1:6333:6333" # gRPC port
      - "127.0.0.1:6334:6334" # REST port
    volumes:
      - qdrant-data:/qdrant/storage
    profiles:
      - qdrant
    restart: always

  chroma:
    image: ghcr.io/chroma-core/chroma:1.0.13
    container_name: tgb-local-chroma
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - chroma-data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
    profiles:
      - chroma
    restart: always
  # --- [ISSUE-28] End of changes: Vector DB Migration ---

volumes:
  redis-db:
  zenml-data:
  
  # --- [ISSUE-28] Start of changes: Vector DB Migration ---
  qdrant-data:
  chroma-data:
  # --- [ISSUE-28] End of changes: Vector DB Migration ---