"""
file: TGB-MicroSuite/services/a-rag/src/core/schemas/llm_schemas.py

Schemas for LLM request and response models using Pydantic.

Defines the data models for input requests to the language model and
the corresponding responses, including validation constraints.
"""

from pydantic import BaseModel, EmailStr, Field


class LLMRequest(BaseModel):
    """
    Request schema for sending input text to the language model (LLM).

    Attributes:
        text (str): Input text prompt to be processed by the LLM.
            Must be at least 1 character long.
        max_tokens (int): Maximum number of tokens to generate in the response.
            Must be greater than 0 and at most 2048.
    """

    text: str = Field(..., min_length=1, description="Input text for the LLM")
    max_tokens: int = Field(
        150, gt=0, le=2048, description="Maximum number of tokens to generate"
    )


class LLMResponse(BaseModel):
    """
    Response schema returned by the language model.

    Attributes:
        generated_text (str): Text generated by the LLM based on the input prompt.
        input_text (str): The original input text sent in the request.
        user_email (EmailStr): Email of the user who made the request.
    """

    generated_text: str
    input_text: str
    user_email: EmailStr


class RAGRequest(BaseModel):
    user_query: str = Field(..., min_length=1)


class RAGResponse(BaseModel):
    answer: str
    original_query: str
    user_email: EmailStr
